import type { VisualMetadata } from './types';

export const VISUAL_CATALOG = {
  'unit1.pronouns.i': {
    id: 'unit1.pronouns.i',
    file: '../../assets/coach/unit1/pronouns/i-david.png',
    alt: 'David se señala a sí mismo para representar el pronombre I',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['David'],
  },
  'unit1.pronouns.you': {
    id: 'unit1.pronouns.you',
    file: '../../assets/coach/unit1/pronouns/you-david.png',
    alt: 'David señala a la persona con quien habla para representar el pronombre you',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['David'],
  },
  'unit1.pronouns.he': {
    id: 'unit1.pronouns.he',
    file: '../../assets/coach/unit1/pronouns/he-carlos.png',
    alt: 'Carlos representa el pronombre he',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['Carlos'],
  },
  'unit1.pronouns.she': {
    id: 'unit1.pronouns.she',
    file: '../../assets/coach/unit1/pronouns/she-maria.png',
    alt: 'María representa el pronombre she',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['María'],
  },
  'unit1.pronouns.we': {
    id: 'unit1.pronouns.we',
    file: '../../assets/coach/unit1/pronouns/we-david-maria.png',
    alt: 'David y María juntos representan el pronombre we',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['David', 'María'],
  },
  'unit1.pronouns.they': {
    id: 'unit1.pronouns.they',
    file: '../../assets/coach/unit1/pronouns/they-carlos-ana.png',
    alt: 'Carlos y Ana juntos representan el pronombre they',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['Carlos', 'Ana'],
  },
  'unit1.pronouns.it': {
    id: 'unit1.pronouns.it',
    file: '../../assets/coach/unit1/pronouns/it-dog-phone.png',
    alt: 'Un perro y un teléfono representan el pronombre it',
    unit: 'unit1',
    category: 'pronouns',
    subjects: ['dog', 'phone'],
  },
  'unit2.to-be.ana-at-work': {
    id: 'unit2.to-be.ana-at-work',
    file: '../../assets/coach/unit2/to-be/ana-at-work.png',
    alt: 'Ana trabaja atendiendo una caja en una tienda',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Ana', 'store', 'work'],
  },
  'unit2.to-be.ana-at-school': {
    id: 'unit2.to-be.ana-at-school',
    file: '../../assets/coach/unit2/to-be/ana-at-school.png',
    alt: 'Ana está en un pasillo escolar con libros, mochila y salones al fondo',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Ana', 'school', 'books', 'backpack', 'inside'],
  },
  'unit2.to-be.carlos-at-work': {
    id: 'unit2.to-be.carlos-at-work',
    file: '../../assets/coach/unit2/to-be/carlos-at-work.png',
    alt: 'Carlos trabaja frente a una computadora en un almacén organizado',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Carlos', 'warehouse', 'work'],
  },
  'unit2.to-be.david-at-home': {
    id: 'unit2.to-be.david-at-home',
    file: '../../assets/coach/unit2/to-be/david-at-home.png',
    alt: 'David descansa en el sofá de su casa',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'home'],
  },
  'unit2.to-be.david-at-the-airport': {
    id: 'unit2.to-be.david-at-the-airport',
    file: '../../assets/coach/unit2/to-be/david-at-the-airport.png',
    alt: 'David está en una puerta de embarque con su equipaje y un avión al fondo',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'airport', 'airplane', 'carry-on', 'inside'],
  },
  'unit2.to-be.david-at-the-restaurant': {
    id: 'unit2.to-be.david-at-the-restaurant',
    file: '../../assets/coach/unit2/to-be/david-at-the-restaurant.png',
    alt: 'David está sentado comiendo dentro de un restaurante',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'restaurant', 'inside'],
  },
  'unit2.to-be.david-at-work': {
    id: 'unit2.to-be.david-at-work',
    file: '../../assets/coach/unit2/to-be/david-at-work.png',
    alt: 'David trabaja atendiendo un escritorio de servicio',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'service desk', 'work'],
  },
  'unit2.to-be.david-happy': {
    id: 'unit2.to-be.david-happy',
    file: '../../assets/coach/unit2/to-be/david-happy.png',
    alt: 'David sonríe con alegría y levanta las manos en una postura celebratoria',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'happy', 'emotion'],
  },
  'unit2.to-be.david-tired': {
    id: 'unit2.to-be.david-tired',
    file: '../../assets/coach/unit2/to-be/david-tired.png',
    alt: 'David bosteza con los ojos cansados mientras sostiene una taza de café',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'tired', 'coffee', 'emotion'],
  },
  'unit2.to-be.david-ready': {
    id: 'unit2.to-be.david-ready',
    file: '../../assets/coach/unit2/to-be/david-ready.png',
    alt: 'David está preparado para salir con mochila, llaves y el pulgar levantado',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'ready', 'backpack', 'keys', 'emotion'],
  },
  'unit2.to-be.carlos-sick': {
    id: 'unit2.to-be.carlos-sick',
    file: '../../assets/coach/unit2/to-be/carlos-sick.png',
    alt: 'Carlos se siente enfermo y descansa en el sofá con una manta, pañuelos y una taza',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Carlos', 'sick', 'blanket', 'tissues', 'cup', 'emotion'],
  },
  'unit2.to-be.maria-happy': {
    id: 'unit2.to-be.maria-happy',
    file: '../../assets/coach/unit2/to-be/maria-happy.png',
    alt: 'María sonríe con alegría y levanta las manos en una postura celebratoria',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Maria', 'happy', 'emotion'],
  },
  'unit2.to-be.ana-ready': {
    id: 'unit2.to-be.ana-ready',
    file: '../../assets/coach/unit2/to-be/ana-ready.png',
    alt: 'Ana está lista para salir con mochila y un libro junto a la puerta de casa',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Ana', 'ready', 'backpack', 'book', 'door', 'emotion'],
  },
  'unit2.to-be.david-in-california': {
    id: 'unit2.to-be.david-in-california',
    file: '../../assets/coach/unit2/to-be/david-in-california.png',
    alt: 'David está en una calle costera de California',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'California', 'outside'],
  },
  'unit2.to-be.david-in-the-office': {
    id: 'unit2.to-be.david-in-the-office',
    file: '../../assets/coach/unit2/to-be/david-in-the-office.png',
    alt: 'David trabaja con una computadora portátil dentro de una oficina',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['David', 'office', 'inside'],
  },
  'unit2.to-be.dog-here': {
    id: 'unit2.to-be.dog-here',
    file: '../../assets/coach/unit2/to-be/it-dog.png',
    alt: 'Max está aquí dentro de una sala',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['Max', 'dog', 'home', 'inside'],
  },
  'unit2.to-be.maria-at-home': {
    id: 'unit2.to-be.maria-at-home',
    file: '../../assets/coach/unit2/to-be/maria-at-home.png',
    alt: 'María descansa en el sofá de su casa',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['María', 'home'],
  },
  'unit2.to-be.maria-at-the-supermarket': {
    id: 'unit2.to-be.maria-at-the-supermarket',
    file: '../../assets/coach/unit2/to-be/maria-at-the-supermarket.png',
    alt: 'María empuja un carrito de compras dentro de un supermercado',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['María', 'supermarket', 'shopping cart', 'groceries', 'inside'],
  },
  'unit2.to-be.maria-at-work': {
    id: 'unit2.to-be.maria-at-work',
    file: '../../assets/coach/unit2/to-be/maria-at-work.png',
    alt: 'María trabaja frente a una computadora',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['María', 'work'],
  },
  'unit2.to-be.maria-in-the-office': {
    id: 'unit2.to-be.maria-in-the-office',
    file: '../../assets/coach/unit2/to-be/maria-in-the-office.png',
    alt: 'María trabaja con una computadora portátil dentro de una oficina',
    unit: 'unit2',
    category: 'scenes',
    subjects: ['María', 'office', 'inside'],
  },
} as const satisfies Record<string, VisualMetadata>;

export type VisualId = keyof typeof VISUAL_CATALOG;
